import { Geist, Geist_Mono } from "next/font/google";
import { MantineProvider } from "@mantine/core"
import "./globals.css";
import '@mantine/core/styles.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
          <meta name="viewport" content="width=750px, initial-scale=1, maximum-scale=1, user-scalable=no" />
        </head>
        <body>
          <MantineProvider>
            {children}
          </MantineProvider>
        </body>
    </html>
  );
}
